### ISSUE TITLE
Not work in silverstripe v4

### ISSUE THREAD

**Issue by adibpwd** [andrewandante/silverstripe-theme-picker#5]
I installed the Bulma theme, then installed this addon, and a dropdown has appeared in the settings, but when I select the theme and save, nothing changes, why?

**Comment by adibpwd** [comment]
If i get cdn bulma in tag head, work in header and footer, but not in content

**Comment by andrewandante** [comment]
Hi @adibpwd - are you referring to this: https://github.com/robertvanlienden/silverstripe-bulma-primary-theme ?

Could you share your theme config please? You'll note this hasn't been updated in a long time so I'll need to blow off a few cobwebs, but I'm happy to take a look 😄 

EDIT:

I've just tried this with a default installation of CMS 4.11.12 and it switches between the simple theme and the bulma-primary theme just fine - so I'll need a few extra things from you if we are to debug. Otherwise, heading to the [Silverstripe Users' Slack](https://www.silverstripe.org/community/slack-signup/) might be a good way to crowd-source the solution (I'm pretty active there too 😉 )

**Comment by adibpwd** [comment]
Problem theme is solved, and now i will get Group Name or Role in user loged

**Comment by andrewandante** [comment]
Okie doke, thanks!
